import {
    getEnvRowByIdForUser,
    getEnvRowBySdkKey,
    getEnvRowsByProjectIdForUser,
    insertEnvRow,
    updateEnvRowSdkKey,
} from '../../db/environment.db.js';
import { pool } from '../../db/index.js';
import { compileDbRowToEnvironment, compileDbRowToEnvWithSdkKey } from '../../loader/environment.loader.js';
import { Environment } from '@flagforge/types';
import crypto from 'crypto';
import { NotFoundError } from '../errors/NotFoundError.js';
import { getEnvIdFromCache, setEnvIdCache } from '../../cache/sdkKey.cache.js';
import { UnauthorizedError } from '../errors/UnauthorizedError.js';

// Creates a new environment for a project
// sdk_key is auto-generated by DB

export async function createEnv(projectId: string, name: string): Promise<Environment> {
    const row = await insertEnvRow(pool, projectId, name);
    return compileDbRowToEnvWithSdkKey(row);
}

export async function resolveEnvByIdForUser(userId: string, envId: string) {
    const row = await getEnvRowByIdForUser(pool, userId, envId);
    if (!row) {
        throw new NotFoundError(`EnvironmentId doesn't exist`);
    }
    return compileDbRowToEnvironment(row);
}

export async function getEnvsByProjectForUser(userId: string, projectId: string): Promise<Environment[]> {
    const rows = await getEnvRowsByProjectIdForUser(pool, userId, projectId);
    return rows.map((row) => compileDbRowToEnvironment(row));
}

export async function rotateEnvSdkKeyForUser(userId: string, envId: string): Promise<string> {
    const newKey = crypto.randomBytes(32).toString('hex');

    const row = await updateEnvRowSdkKey(pool, userId, envId, newKey);
    if (!row) {
        throw new NotFoundError('Environment not found');
    }
    return newKey;
}

export async function resolveEnvIdFromSdkKey(sdkKey: string): Promise<string> {
    const envId = await getEnvIdFromCache(sdkKey);
    if (envId) {
        return envId;
    }
    const row = await getEnvRowBySdkKey(pool, sdkKey);
    if (!row) {
        throw new UnauthorizedError('Invalid SDK key');
    }
    setEnvIdCache(sdkKey, row.id).catch(console.error);
    return row.id;
}
